package config

import (
	"fmt"
	"gopkg.in/yaml.v2"
	"os"
)

type AppConfig struct {
	API    API    `yaml:"api"`
	DBConf DBConf `yaml:"db"`
}

type API struct {
	Port    string `yaml:"port"`
	AppName string `yaml:"app_name"`
}
type DBConf struct {
	URL      string `yaml:"url"`
	MaxConns int32  `yaml:"max_conns"`
}

func ReadConfigFromFile(filename string) (*AppConfig, error) {
	// Read the file contents
	data, err := os.ReadFile(filename)
	if err != nil {
		return nil, fmt.Errorf("failed to read file: %w", err)
	}

	// Unmarshal the YAML data into an AppConfig struct
	var autoGenerated AppConfig
	if err := yaml.Unmarshal(data, &autoGenerated); err != nil {
		return nil, fmt.Errorf("failed to unmarshal YAML data: %w", err)
	}

	return &autoGenerated, nil
}
