// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	dto "github.com/petara94/go-auth/internal/transport/http/api/dto"
	mock "github.com/stretchr/testify/mock"
)

// UserGroupRepository is an autogenerated mock type for the UserGroupRepository type
type UserGroupRepository struct {
	mock.Mock
}

type UserGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserGroupRepository) EXPECT() *UserGroupRepository_Expecter {
	return &UserGroupRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: group
func (_m *UserGroupRepository) Create(group dto.UserGroup) (*dto.UserGroup, error) {
	ret := _m.Called(group)

	var r0 *dto.UserGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.UserGroup) (*dto.UserGroup, error)); ok {
		return rf(group)
	}
	if rf, ok := ret.Get(0).(func(dto.UserGroup) *dto.UserGroup); ok {
		r0 = rf(group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.UserGroup) error); ok {
		r1 = rf(group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGroupRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserGroupRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - group dto.UserGroup
func (_e *UserGroupRepository_Expecter) Create(group interface{}) *UserGroupRepository_Create_Call {
	return &UserGroupRepository_Create_Call{Call: _e.mock.On("Create", group)}
}

func (_c *UserGroupRepository_Create_Call) Run(run func(group dto.UserGroup)) *UserGroupRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.UserGroup))
	})
	return _c
}

func (_c *UserGroupRepository_Create_Call) Return(_a0 *dto.UserGroup, _a1 error) *UserGroupRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserGroupRepository_Create_Call) RunAndReturn(run func(dto.UserGroup) (*dto.UserGroup, error)) *UserGroupRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function with given fields: id
func (_m *UserGroupRepository) DeleteByID(id uint64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserGroupRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type UserGroupRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - id uint64
func (_e *UserGroupRepository_Expecter) DeleteByID(id interface{}) *UserGroupRepository_DeleteByID_Call {
	return &UserGroupRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", id)}
}

func (_c *UserGroupRepository_DeleteByID_Call) Run(run func(id uint64)) *UserGroupRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *UserGroupRepository_DeleteByID_Call) Return(_a0 error) *UserGroupRepository_DeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserGroupRepository_DeleteByID_Call) RunAndReturn(run func(uint64) error) *UserGroupRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *UserGroupRepository) GetByID(id uint64) (*dto.UserGroup, error) {
	ret := _m.Called(id)

	var r0 *dto.UserGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*dto.UserGroup, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) *dto.UserGroup); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGroupRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserGroupRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint64
func (_e *UserGroupRepository_Expecter) GetByID(id interface{}) *UserGroupRepository_GetByID_Call {
	return &UserGroupRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *UserGroupRepository_GetByID_Call) Run(run func(id uint64)) *UserGroupRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *UserGroupRepository_GetByID_Call) Return(_a0 *dto.UserGroup, _a1 error) *UserGroupRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserGroupRepository_GetByID_Call) RunAndReturn(run func(uint64) (*dto.UserGroup, error)) *UserGroupRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: group
func (_m *UserGroupRepository) Update(group dto.UserGroup) (*dto.UserGroup, error) {
	ret := _m.Called(group)

	var r0 *dto.UserGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.UserGroup) (*dto.UserGroup, error)); ok {
		return rf(group)
	}
	if rf, ok := ret.Get(0).(func(dto.UserGroup) *dto.UserGroup); ok {
		r0 = rf(group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.UserGroup) error); ok {
		r1 = rf(group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGroupRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserGroupRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - group dto.UserGroup
func (_e *UserGroupRepository_Expecter) Update(group interface{}) *UserGroupRepository_Update_Call {
	return &UserGroupRepository_Update_Call{Call: _e.mock.On("Update", group)}
}

func (_c *UserGroupRepository_Update_Call) Run(run func(group dto.UserGroup)) *UserGroupRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.UserGroup))
	})
	return _c
}

func (_c *UserGroupRepository_Update_Call) Return(_a0 *dto.UserGroup, _a1 error) *UserGroupRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserGroupRepository_Update_Call) RunAndReturn(run func(dto.UserGroup) (*dto.UserGroup, error)) *UserGroupRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUserGroupRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserGroupRepository creates a new instance of UserGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserGroupRepository(t mockConstructorTestingTNewUserGroupRepository) *UserGroupRepository {
	mock := &UserGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
